---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache2 and php  packages for Ubuntu
    apt:
      name:
        -  apache2
        - libapache2-mod-php

      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for Cent OS
    yum: 
      update_cache: yes
    when: ansible_distribution_version == "CentOS"

  - name: install apache  php packages for CentOS
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
