---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache2 package
    apt:
      name:
        -  apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for Cent OS
    dnf: 
      update_cache: yes
    when: ansible_distribution_version == "CentOS"

  - name: install php package for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
